algorandfoundation/algokit-lora

package-lock.json
package.json
src/features/assets/components/asset-details.tsx
src/features/assets/utils/add-https-scheme-if-needed.ts
src/features/transactions/components/asset-config-transaction-info.tsx

- Add https scheme to asset links if not present
- Update subscriber-ts package, to fix noop on completion sometimes getting marked as update

fix: add https scheme to links if not present and update subscriber-ts

---

src/features/transactions/mappers/app-call-transaction-mappers.ts

fix: check approval and clear when checking if opup

---

src/features/settings/components/clear-cache.tsx
src/features/settings/components/settings.tsx
src/features/wallet/components/connect-wallet-button.tsx
src/features/wallet/data/clear-active-wallets.ts
src/features/wallet/hooks/use-disconnect-wallet.ts
src/features/wallet/utils/clear-available-wallets.ts

A button in settings to clear all cached data and disconnect connected wallet.

feat: clear cache button

---

src/features/transactions/components/key-reg-transaction-info.tsx
src/features/transactions/mappers/key-reg-transaction-mappers.ts

Fixes https://github.com/algorandfoundation/algokit-lora/issues/162

fix: correctly mark an online key reg

---

src/features/assets/data/asset-metadata.ts
src/features/assets/data/types.ts
src/features/assets/mappers/asset.ts
src/features/assets/pages/asset-page.test.tsx
src/tests/object-mother/asset-result.ts
src/tests/object-mother/transaction-result.ts

Fixes https://github.com/algorandfoundation/algokit-lora/issues/158

fix: handle an asset which uses both arc-3 and arc-69

---

src/features/app-interfaces/data/index.ts
src/features/blocks/data/genesis-hash.ts
src/features/blocks/data/latest-blocks.ts
src/features/common/data/data-store.ts
src/features/common/data/indexed-db.ts
src/features/groups/pages/group-page.test.tsx
src/features/transactions/pages/transaction-page.test.tsx

https://github.com/user-attachments/assets/8d905567-12ba-4bc4-8ced-5c8be456ea15

feat: use network genesis hash in the db name

---

package-lock.json
src/features/applications/mappers/index.ts

fix: validating values in application global state

---

package-lock.json
package.json
src/features/app-interfaces/components/create-app-interface-dialog-body.test.tsx
src/features/app-interfaces/components/create-app-interface-dialog-body.tsx
src/features/app-interfaces/components/create-app-interface-form.tsx
src/features/app-interfaces/components/delete-app-interface-button.tsx
src/features/app-interfaces/components/deploy-app-form.tsx

- Update to the latest utils-ts
- Updating to use algorandclient deployment client
- Remove `On Update` and `On Schema Break` as they aren't need in the context of a create
- Hide `Updatable` and `Deletable` checkboxes when not applicable

chore: deployment tweaks

---

src/features/applications/components/application-box-details-dialog.tsx
src/features/applications/mappers/index.ts
src/utils/base64-to-utf8.ts

chore: utf-8 decode box info where applicable

---

package-lock.json
package.json
src/features/applications/mappers/index.ts
src/features/common/data/atom-storage.ts
src/features/layout/components/left-side-bar-menu.tsx
src/features/network/data/index.ts

- Also activate the transaction wizard menu item.

chore: prevent tab sync of the selected network

---

src/features/assets/mappers/asset-summary.ts

fix: use name-b64 in case there is no name

---

src/features/accounts/components/account-link.tsx
src/features/accounts/components/address-or-nfd-link.tsx
src/features/applications/components/confirm-transactions-resources-form.tsx
src/features/forms/components/address-form-item.tsx
src/features/forms/components/form-field-helper.tsx
src/features/nfd/data/is-nfd.ts
src/features/search/data/search.ts
src/features/transaction-wizard/components/account-close-transaction-builder.tsx
src/features/transaction-wizard/components/app-call-transaction-builder.tsx
src/features/transaction-wizard/components/asset-clawback-transaction-builder.tsx
src/features/transaction-wizard/components/asset-create-transaction-builder.tsx
src/features/transaction-wizard/components/asset-destroy-transaction-builder.tsx
src/features/transaction-wizard/components/asset-freeze-transaction-builder.tsx
src/features/transaction-wizard/components/asset-opt-in-transaction-builder.tsx
src/features/transaction-wizard/components/asset-opt-out-transaction-builder.tsx
src/features/transaction-wizard/components/asset-reconfigure-transaction-builder.tsx
src/features/transaction-wizard/components/asset-transfer-transaction-builder.tsx
src/features/transaction-wizard/components/key-registration-transaction-builder.tsx
src/features/transaction-wizard/components/method-call-transaction-builder.tsx
src/features/transaction-wizard/components/payment-transaction-builder.tsx
src/features/transaction-wizard/components/transactions-builder.test.tsx
src/features/transaction-wizard/data/common.ts
src/features/transaction-wizard/mappers/app-call.ts
src/features/transaction-wizard/mappers/as-address-or-nfd.ts
src/features/transaction-wizard/mappers/as-algosdk-transactions.ts
src/features/transaction-wizard/mappers/as-description-list-items.tsx
src/features/transaction-wizard/models/index.ts
src/features/transactions-graph/components/__snapshots__/application-transaction-graph.DX64C5POMYLPSMOZVQZWF5VJ7RW27THYBUGKNH5T4A5D2KAFHZCQ.html
src/features/transactions-graph/components/vertical-title.tsx

feat: add NFD support in transaction builder forms

---

src/features/transaction-wizard/components/group-send-results.tsx

Fix the simulate trace filename to ensure appl transactions are correctly accounted for.

fix: adjust trace filename

---

package-lock.json
package.json
src/features/blocks/components/block-details.tsx
src/features/blocks/data/latest-blocks.ts
src/features/blocks/data/types.ts
src/features/blocks/mappers/index.ts
src/features/blocks/models/index.ts
src/features/blocks/pages/block-page.test.tsx
src/tests/builders/block-result-builder.ts

chore: add proposer to block descriptions

---

.github/workflows/preview-app.yaml

This adds a workflow that adds a cloudflare pages preview app for each pull request.

Added deploy preview app workflow

---

src/features/abi-methods/data/abi-method.ts

bug: get latest appspec when there is no confirmed-round

---

src/features/transactions/components/latest-transactions.tsx
src/features/transactions/components/transaction-type-badge.tsx
src/features/transactions/components/transactions-table-columns.tsx

feat: use transaction type badge in the table

---

src/features/common/components/prompt-form.tsx

This prompt is used in connecting and signing scenario, so I think OK is a better value.

chore: tweak prompt button text

---

package-lock.json
package.json
tailwind.config.js

Updated vitest to 2.1.9 (the patched version)
Did an override for the patched esbuild 0.25.0
Fixed the rest with npm audit fix

fix: updated deps to fix vunerabilities

---

README.md
package-lock.json
src/features/transactions/mappers/asset-transfer-transaction-mappers.ts

Updated dev portal links
**DO NOT MERGE UNTIL INSTRUCTED**

AK-194: Update dev portal links

---

src/features/applications/data/application-boxes.ts

The box value was being decoded incorrectly.

fix: simplify application box data handling with direct base64 encoding

---

.github/workflows/release-desktop.yaml

The bot wasn't working so I reverted to GITHUB_TOKEN

fix: reverted back to using GITHUB_TOKEN

---

.gitignore
.vscode/settings.json
package.json
src/features/accounts/data/funded-account.ts
src/features/accounts/data/index.ts
src/features/assets/components/asset-details.tsx
src/features/assets/components/labels.ts
src/features/assets/data/asset-metadata.ts
src/features/assets/data/circulating-supply.ts
src/features/assets/data/types.ts
src/features/assets/mappers/asset.ts
src/features/assets/models/index.ts
src/features/assets/pages/asset-page.test.tsx
src/features/assets/utils/arc62.ts
src/features/network/data/index.ts
src/tests/object-mother/application-result.ts
src/tests/object-mother/asset-result.ts
src/tests/utils/arc62.test.ts

Fixes up and squashes #484 with a single singed commit, so it can be merged.

feat: add support for rendering arc62 circulating supply of an asset

---

.github/workflows/release-web.yaml

Works around https://github.com/netlify/cli/issues/7671

fix: resolve netlify deploy issue
