algorandfoundation/algokit-lora

src/features/transactions-graph/components/__snapshots__/application-transaction-graph.DX64C5POMYLPSMOZVQZWF5VJ7RW27THYBUGKNH5T4A5D2KAFHZCQ.html
src/features/transactions-graph/components/horizontal.tsx
src/features/transactions-graph/mappers/horizontals.ts
src/features/transactions-graph/mappers/verticals.ts
src/features/transactions-graph/models/index.ts
src/features/transactions/components/app-call-transaction-info.tsx
src/features/transactions/components/transaction-type-description-details.tsx
src/features/transactions/mappers/app-call-transaction-mappers.ts
src/features/transactions/models/index.ts
src/features/transactions/pages/transaction-page.test.tsx

Completes #148 
- Adjust transaction visualiser labels to better represent the thing that is happening, rather than simply reflection the transaction type
- Adjust app call transaction `subType` and `action` fields to better align with other transaction types.

feat: adjust visual transaction label to better represent friendly names for transactions

---

src/features/forms/components/checkbox-form-item.tsx
src/features/forms/components/multi-select-form-item.tsx
src/features/network/components/create-network-config-form.tsx
src/features/network/components/network-configs-table.tsx
src/features/network/data/index.ts
src/features/network/pages/network-page.tsx

**Features**
- Allow temporary customisation of the localnet config using url search params. This is used when launching lora via `algokit explore localnet` inside a GitHub codespace.
**Fixes**
- Set selected network to localnet when deleting a custom network that is currently selected.
- Reset data provider when resetting the settings of a default network that has been modified and is currently selected.
- Disallow creating custom networks with the name `settings` or `app-studio`, as they collide with app routes and will cause weird behaviours.
- Add id to multiselect so the label is valid.

feat: temporary localnet config

---

src/features/explore/data/live-explorer.ts
src/features/explore/pages/explore-page.test.tsx
src/features/explore/pages/explore-page.tsx

Fixes https://github.com/algorandfoundation/algokit-lora/issues/164
The below shows the behaviour before (right) and after (left). Wait until the end.

fix: don't limit latest transactions to the latest 10 blocks

---

src/features/network/pages/network-page.tsx

Resolves https://github.com/algorandfoundation/algokit-lora/issues/166
When changing networks, the browser history will still contain explore routes from the previous network selection.
These explore routes will likely result in 404s, as the id's don't apply to the active network.
Instead of 404'ing, navigate (and replace the route in history) to the explore page for the active network.

chore: adjust history when changing networks

---

.nsprc
package-lock.json
src/features/abi-methods/data/abi-method.test.tsx
src/features/abi-methods/data/abi-method.ts
src/features/search/components/search.test.tsx
src/tests/object-mother/transaction-result.ts

For create app transactions, algod return undefined for `application-id` field. This caused an issue with the logic to fetch app spec from indexed db.

bug: handle create application transactions received from algod

---

src/features/transactions-graph/components/__snapshots__/application-transaction-graph.INDQXWQXHF22SO45EZY7V6FFNI6WUD5FHRVDV6NCU6HD424BJGGA.html
src/features/transactions-graph/components/__snapshots__/application-transaction-graph.WYEGSIGWZHTR6VYXC3EXFGZQHYKI6FQOZU2DOKHQCAWYEIHJBKEA.html
src/features/transactions-graph/components/__snapshots__/group-graph.%2FoRSr2uMFemQhwQliJO18b64Nl1QIkjA39ZszRCeSCI%3D.html
src/utils/compact-amount.ts

I have changed the line in [https://github.com/algorandfoundation/algokit-lora/blob/main/src/utils/compact-amount.ts#L4](url) from 8 to 9 for echancement #238 .
First i have tested out the scenario by making a transaction [http://localhost:1420/testnet/transaction/HZXSLRMSVSHXYH3VILN62EFLZD6Y3XNOQPDTJ2QGJV73IJLI3U4Q](url) as which was discussed in discord [https://discord.com/channels/491256308461207573/1277185471214256138](url) and got below visual image which looks good & all 6 digits are visible.
**Previous Snapshot -**
**Updated Snapshot -**
I have ran the tests & got 3 errors in the following transactions due to snapshot mismatch
1. [http://localhost:1420/mainnet/transaction/WYEGSIGWZHTR6VYXC3EXFGZQHYKI6FQOZU2DOKHQCAWYEIHJBKEA](url) - 
**Previous Snapshot -**
**Updated Snapshot -** …

Transaction visualiser amount rounding #238

---

src/features/transactions/mappers/transaction-summary-mappers.ts

When creating an app, the latest transactions component was showing the "to" as 0

fix: use created app id in transaction summary, when creating an app

---

src/features/transaction-wizard/components/group-send-results.tsx
src/features/transactions-graph/components/__snapshots__/application-transaction-graph.DX64C5POMYLPSMOZVQZWF5VJ7RW27THYBUGKNH5T4A5D2KAFHZCQ.html
src/features/transactions-graph/components/app-call-transaction-tooltip-content.tsx
src/features/transactions-graph/components/asset-config-transaction-tooltip-content.tsx
src/features/transactions-graph/components/transactions-graph.tsx
src/features/transactions-graph/components/vertical-title.tsx
src/features/transactions/data/send-transaction-result.ts

Also fixed a styling issue and made assetId/applicationId in the transaction visual not clickable when simulated.

fix: error when sending an app call that does an asset create

---

.nsprc
package-lock.json
package.json

There currently `npm audit` failure for cross-spawn package. I tried to use override for that package, but it didn't work because it's a bundled dep of a direct dep. These don't get updated with override. There is a [discussion of this in this issue here](https://github.com/npm/cli/issues/7902). Once that gets resolved, we can update the package.
https://github.com/npm/cli/issues/7902

fix: added exception for cross-spawn audit failure until fixed

---

.nsprc

The id of the cross-spawn audit ignore has changed, this PR updates it.

chore: update id of cross-spawn audit ignore

---

.nsprc
package-lock.json
package.json
src/features/abi-methods/utils/parse-errors.ts
src/features/applications/components/application-method-definitions.tsx
src/features/transaction-wizard/components/transactions-builder.tsx

When we can parse the error
When we can't parse the error

feat: friendly ARC56 error messages

---

src/assets/icons/claw.svg

We removed the css classes from the claw react component, however the source svg wasn't updated.

chore: update claw icon source

---

.github/actions/build-linux/action.yaml
.github/workflows/release.yaml
package-lock.json
package.json

I can't test the Tauri build fully due to there were no code signing certs setup. I can confirm that the build works all the way to right before code signing.

chore: environment variable substitution for the Tauri build

---

src/features/assets/data/asset-metadata.ts

https://lora.algokit.io/mainnet/asset/607591690 for example has a CORS and expired domain issue.

fix: handle and log error when failing to fetch asset metadata

---

package-lock.json
src/features/app-interfaces/components/create/deploy-app.tsx
src/features/app-interfaces/pages/create-app-interface-page.tsx
src/features/common/components/wallet-provider.tsx
src/features/forms/components/address-form-item.tsx
src/features/fund/components/localnet-funding.tsx
src/features/transaction-wizard/components/account-close-transaction-builder.tsx
src/features/transaction-wizard/components/app-call-transaction-builder.tsx
src/features/transaction-wizard/components/method-call-transaction-builder.tsx
src/features/transaction-wizard/components/payment-transaction-builder.tsx
src/features/transaction-wizard/components/transactions-table.tsx
src/features/transaction-wizard/mappers/as-description-list-items.tsx
src/features/transaction-wizard/models/index.ts
src/features/wallet/components/connect-wallet-button.tsx

- Allow 0 ALGO amounts when creating pay transactions
- Allow setting the extra program pages when deploying an app
- Tweak UX KMD and Mnemonic wallet provider modal presentation
- Don't prompt for a KMD wallet password for the `unencrypted-default-wallet` or `lora-dev` wallets, as they don't have one.

tweaks to txn wizard and app lab based on feedback

---

src/features/wallet/data/active-wallet.ts

This fixes the problem, however we'll need to dig more into why.

fix: block polling fails with wallet connected

---

package-lock.json
package.json
src/features/abi-methods/mappers/form-schema-mappers.ts
src/features/app-interfaces/components/create/from-app-id-card.tsx
src/features/applications/components/confirm-transactions-resources-form.tsx
src/features/forms/data/common.ts
src/features/transaction-wizard/components/asset-clawback-transaction-builder.tsx
src/features/transaction-wizard/components/asset-destroy-transaction-builder.tsx
src/features/transaction-wizard/components/asset-freeze-transaction-builder.tsx
src/features/transaction-wizard/components/asset-opt-in-transaction-builder.tsx
src/features/transaction-wizard/components/asset-opt-out-transaction-builder.tsx
src/features/transaction-wizard/components/asset-reconfigure-transaction-builder.tsx
src/features/transaction-wizard/components/asset-transfer-transaction-builder.tsx
src/features/transaction-wizard/mappers/as-algosdk-transactions.ts
src/features/transaction-wizard/models/index.ts
src/utils/as-json.ts

- Support decimal asset transfer values over the limits of number
- Refine asJson to convert to number where applicable
- Fix zod bigInt schema usage

fix: support asset transfers for decimal values over the safe number value

---

package-lock.json
package.json
src/features/abi-methods/utils/parse-errors.ts
src/features/transaction-wizard/utils/transform-search-params-transactions.ts

- Fix handling of uint state delta mapping
- Fix logic error parsing when rendering ARC56 error messages

fix: resolve some algosdk@3 behaviour differences

---

index.html

Added plausible snippet to start collecting data

feat: Added plausible snippet

---

src/features/app-interfaces/components/create/from-app-id-card.tsx
src/features/app-interfaces/components/create/from-deployment-card.tsx
src/features/fund/components/fund-account-form.tsx
src/features/transaction-wizard/components/transactions-builder.tsx

Added the following plausible analytic events according to [these instructions](https://plausible.io/docs/custom-event-goals):
app-lab-use-existing-app-id
app-lab-deploy-new-app
txn-wizard-add-txn
txn-wizard-simulate-txn
txn-wizard-send-txn
fund-account-form-create-and-fund
fund-account-form-fund

feat: Added plausible custom events

---

package-lock.json
package.json

Updating the subscriber-ts version, so that blocks reward synthetic pay transactions (added in https://github.com/algorandfoundation/algokit-subscriber-ts/pull/110) are surfaced.

feat: update subscriber which enables block reward synthetic transactions

---

package-lock.json
src/features/blocks/data/block-result.ts
src/features/transactions/components/payment-transaction-info.tsx

Moving here means that the mapping is run as part of deconstructing the block that is fetched in the background.
This should help surface any issues quicker.
I also noticed that `closeAmount` doesn't appear to be available in the model.

chore: move wasm test to the block mapping

---

index.html

Moved the tracking script to just before the </body> so that any kind of blocking script doesn't interfere with page loading.

chore: move tracking script to ensure it doesn't interfere when blocked

---

src/features/transaction-wizard/components/asset-create-transaction-builder.tsx
src/features/transaction-wizard/components/payment-transaction-builder.tsx
src/features/transaction-wizard/utils/transactions-url-search-params.test.tsx
src/features/transaction-wizard/utils/transform-search-params-transactions.ts

Added Payment and asset create transaction to search params
**Commit 1** 
Added the core infrastructure for payment transaction URL search params. Built useTransactionSearchParamsBuilder hook that parses URL parameters like type[0]=pay&sender[0]=ADDRESS&amount[0]=1000000 and transforms them into transaction objects that automatically populate the wizard forms.
Test params
minimal payment
https://db31f5ca.algokit-lora.pages.dev/mainnet/transaction-wizard?type[0]=pay&sender[0]=I3345FUQQ2GRBHFZQPLYQQX5HJMMRZMABCHRLWV6RCJYC6OO4MOLEUBEGU&receiver[0]=AAOLENX3Z76HBMQOLQF4VW26ZQSORVX7ZQJ66LCPX36T2QNAUYOYEY76RM&amount[0]=2500000
full payment
https://db31f5ca.algokit-lora.pages.dev/mainnet/transaction-wizard?type[0]=pay&sender[0]=I3345FUQQ2GRBHFZQPLYQQX5HJMMRZMABCHRLWV6RCJYC6OO4MOLEUBEGU&receiver[0] …

Added payment and asset create txn to url params AK-653 AK-654

---

src/features/transactions/components/transactions-table-columns.tsx
src/features/transactions/mappers/payment-transaction-mappers.ts
src/features/transactions/models/index.ts
src/features/transactions/pages/transaction-page.test.tsx

Update the transaction table columns logic to render payment txn with close remainder. After this change, the close remainder to and amount fields are rendered on the transaction table.

feat: render payment txn with close remainder

---

.github/workflows/release-desktop.yaml
.github/workflows/release-web.yaml
.github/workflows/release.yaml
src-tauri/Cargo.lock

There are currently errors in  the promote-to-prod workflow when running the release workflow. The release-desktop and release-web workflows are called from the release workflow, which means the secrets are passed automatically. The secrets were already being inherited but not imported by the workflow, so i added them. 
These are some other updates
- Added validation for missing release outputs that are needed crabnebula steps
- Updated the conflict resolution in the sync-to-main job because it was failing on merge conflicts.

fix: added secrets to workflow_call workflows
